runtime: nodejs

env: flex

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)

  - url: /favicon.ico
    static_files: /favicon.ico
    upload: /favicon.ico